### ISSUE TITLE
FallbackAPIServer SkinDomain

### ISSUE THREAD

**Issue by catfromplan9** [unmojang/drasl#10]
What would it be on authlib injector

**Comment by evan-goode** [comment]
It's whatever domains their skins are hosted on.
That info should be returned by the root of their API, for Blessing Skin go to: https://skin.prinzeugen.net/api/yggdrasil/

and it returns `{ ... "skinDomains":["skin.prinzeugen.net"], ...}`

It may not always be the same as their website.

**Comment by catfromplan9** [comment]
Thanks, I assumed this by reading the code. Noticed that it appends this url to Domains and domains is just the domain config for the existing auth server
