### ISSUE TITLE
API

### ISSUE THREAD

**Issue by evan-goode** [unmojang/drasl#18]
Drasl should have an API other than the Web UI.
- [x] Each user gets a random API token that can be invalidated and re-rolled
- [x] Refactor front.go to share code with API routes
- [x] Update user's own profile
- [x] Admin actions: delete user, change password, lock account
- [x] Create invite
- [x] Documentation
- [x] Tests

**Comment by fnxln** [comment]
i have a project in mind to use such features, ill be up to implement such features in a pull request
but what libraries would be good for the project or using the std is sufficient?

besides,
thx for the awsome project 💜

**Comment by evan-goode** [comment]
> i have a project in mind to use such features, ill be up to implement such features in a pull request but what libraries would be good for the project or using the std is sufficient?

I think implementing the (likely JSON) HTTP API will require significant rewriting/refactoring, so I would rather do it myself. But it is a high priority, it's the very next thing I'm planning to do with this project.

We already use the web framework Echo; I don't think we will need to bring in any new dependencies.

Is there any specific functionality you'd like in the HTTP API? It'll definitely be able to do anything the admin web interface can do, plus registering new accounts.

> besides, thx for the awsome project 💜

You're welcome! Thanks!

**Comment by evan-goode** [comment]
This is done for now, though the API will need some breaking changes after implementing https://github.com/unmojang/drasl/issues/75 and https://github.com/unmojang/drasl/issues/39, and some example code for interacting with it would be good to have.
