### ISSUE TITLE
slim variant is not slim

### ISSUE THREAD

**Issue by matheus20337** [unmojang/drasl#37]
For some reason, the game ignores my skin model setting and assumes every skin is classic.
![website-vs-ingame](https://github.com/unmojang/drasl/assets/149222182/f73ec7f6-1fb4-4c59-a3f7-be1411ed9292)

### What I think the problem is
According to [this site](https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape), `/session/minecraft/profile/<uuid>` should return something like this:
```json
{
    "id": "<profile identifier>",
    "name": "<player name>",
    "properties": [ 
        {
            "name": "textures",
            "value": "<base64 string>",
            "signature": "<base64 string; signed data using Yggdrasil's private key>" // Only provided if ?unsigned=false is appended to url
        }
    ],
    "profileActions": []
}
```
And value should decode to something like this:
```json
{
    "timestamp": <java time in ms>,
    "profileId": "<profile uuid>",
    "profileName": "<player name>",
    "signatureRequired": true, // Only present if ?unsigned=false is appended to url
    "textures": {
        "SKIN": {
            "url": "<player skin URL>",
            "metadata": {
                "model": "slim"
            }
        },
        "CAPE": {
            "url": "<player cape URL>"
        }
    }
}
```
However, my test account returns this:
```json
{
    "timestamp":1701318253009455404,
    "profileId":"418bb580c44045a5bf3996f200b91c57",
    "profileName":"tester",
    "textures":
    {
        "SKIN": 
            {
"url":"https://drasl.localhost.lnet/drasl/texture/skin/676d6f7657076d3ee60f6e2b33e59cbbbb33dc6dbcf5242ccbceebf10773f71d.png",
        "model":
            {
                "string":"slim"
            }
        }
    }
}
```
There is no `"metadata"` block.

**Please note that I don't know what I'm doing and that this is just a guess.**

###  My setup
OS: Artix Linux
Drasl: 1.0.0 (from the AUR)
Launcher: PollyMC

**Comment by evan-goode** [comment]
Thanks for the detailed report, yep, that's a goof. The session routes are not well-tested yet. Fixed in https://github.com/unmojang/drasl/pull/38, I'll merge that once the CI finishes and tag 1.0.1.
