### ISSUE TITLE
Drasl webserver doesn't work (Docker)

### ISSUE THREAD

**Issue by GoodGameInfinity** [unmojang/drasl#44]
Hello! I have tried to set up Drasl on my server using Docker, but when I try to access the web UI or even ping the HTTP server it's running on the port is closed. And the thing is that I am not even connecting from the internet, but from my local network. I made sure that the port is accessible from the computer I'm trying to reach the HTTP server from, so I think that it must by an issue with Drasl. According to the logs which I have supplied below the webserver starts normally.

What I have tried to do (but it didn't help)
- Changing the port
- Messing with the config
- Purposefully making the server throw an error to check if it even works (it does btw)

Here is my config file:
```
# Drasl default config file

# Example: drasl.example.com
Domain = "mcauth.frnsrv.ru"

# Example: My Drasl Instance
InstanceName = "REDACTED"

# Example: My Organization
ApplicationOwner = "REDACTED"

# Example: 127.0.0.1:25585
ListenAddress = "127.0.0.1:15585"

# Example: https://drasl.example.com
BaseURL = "https://mcauth.frnsrv.ru"

# List of usernames who automatically become admins of the Drasl instance
DefaultAdmins = ["GoodGameInfinity"]

# Amount of time until token expires in seconds, example: 604800 (1 week)
TokenExpireSec = 604800

[RegistrationNewPlayer]
Allow = true
AllowChoosingUUID = false
RequireInvite = true
```

Here are the logs copied from docker:
```
2023/12/23 20:24:42 Loading config from /etc/drasl/config.toml

2023/12/23 20:24:42 No users found! Here's an invite URL: https://mcauth.frnsrv.ru/drasl/registration?invite=REDACTED

⇨ http server started on 127.0.0.1:15585
```

Also some info:
I used Portainer to set up the docker container, it publishes the port 15585/TCP and mounts two binds. The Docker image I used is unmojang/drasl:latest from the Docker Hub.

**Comment by GoodGameInfinity** [comment]
Also just saying that I have tried running it on my main machine with the same config using the AUR version, and it doesn't work on it either.

**Comment by evan-goode** [comment]
Hi, sounds like a configuration error. I'm not familiar with Portainer, but if you stop by the #help channel on Matrix: https://matrix.to/#/#unmojang:matrix.org, I can try to help. My first thought is you may be missing the reverse proxy to handle the HTTPS.

**Comment by GoodGameInfinity** [comment]
For anyone who encounters the issue: the thing that fixed it for me, was changing the ListenAddress IP from 127.0.0.1 to 0.0.0.0

**Comment by Goosegit11** [comment]
Can confirm that changing ListenAddress helped with that issue

**Comment by evan-goode** [comment]
Maybe, but I'd rather it be secure-by-default. You don't want Drasl exposed on :25585 to the Internet since someone might accidentally authenticate over HTTP and not HTTPS. So it is safer to only listen on localhost by default. The docker-caddy example in the repository is a good starting point for a correct Docker deployment. 

This should be mentioned in troubleshooting.md though, and maybe made more clear in installation.md.

**Comment by Goosegit11** [comment]
Why it doesn't work with 127.0.0.1 then? I have Drasl and reverse proxies on different machines (and IPs) if that makes a difference

**Comment by Goosegit11** [comment]
oh wait i'm so stupd
