### ISSUE TITLE
Add a config option for accessing API endpoints without a subdirectory

### ISSUE THREAD

**Issue by catfromplan9** [unmojang/drasl#59]
This is useful for users who would like to attempt more advanced configurations e.g. using unsupported launchers by editing hosts file and installing a self signed SSL certificate. So /account/users/profiles/minecraft/player is also accessible via /users/profiles/minecraft/player

**Comment by evan-goode** [comment]
This should already work: https://github.com/unmojang/drasl/blob/72d3b1cd328e55370da0efd1b94f2b624487a50f/main.go#L206

All the routes should already be accessible without the /account, /services etc. prefix.

**Comment by catfromplan9** [comment]
> This should already work:
> 
> https://github.com/unmojang/drasl/blob/72d3b1cd328e55370da0efd1b94f2b624487a50f/main.go#L206
> 
> All the routes should already be accessible without the /account, /services etc. prefix.

Oh, wonderful, thank you!
