### ISSUE TITLE
Drasl doesn't check for special characters in username 

### ISSUE THREAD

**Issue by IkyMax** [unmojang/drasl#73]
As said in the title, Drasl doesn't check for valid usernames, it allows special characters such as ñ, æ, å, ę, ç and many others, it doesn't even check for spaces on characters usernames (test test) and it can happen what a space is set after the username (such as "test "), causing weird Issues on a Minecraft server.

**Comment by evan-goode** [comment]
Thanks, yeah you're right, the default should probably be to not allow "exotic" player names. I opened https://github.com/unmojang/drasl/pull/74.

**Comment by IkyMax** [comment]
Nice! Do you want me to test it?

**Comment by evan-goode** [comment]
Sure! Thanks

**Comment by IkyMax** [comment]
Hey! it works, thx! Will you be pushing this and the client token changes anytime soon into the docker image?

**Comment by evan-goode** [comment]
Fixed in https://github.com/unmojang/drasl/pull/74
