### ISSUE TITLE
what is SetSkinURL for authlib-injector auth server

### ISSUE THREAD

**Issue by catfromplan9** [unmojang/drasl#9]
Title

**Comment by evan-goode** [comment]
Haha I'm halfway through writing the config docs, `SetSkinURL` should be a link to the web page where you set your skin on the auth server. So for Mojang it's https://www.minecraft.net/msaprofile/mygames/editskin. You could use the home page of the authlib-injector service, assuming it has one.

it's not important to set that option, currently it's only used for the "challenge skin" feature.

**Comment by catfromplan9** [comment]
Ah lol just found it as u said this, i assume itd be /skinlib/upload

**Comment by catfromplan9** [comment]
And I can use my authlib injector auth server as fallback to allow either, so i can migrate my players over time before full deprecation of the authlib injector server?

**Comment by catfromplan9** [comment]
> Ah lol just found it as u said this, i assume itd be /skinlib/upload

And maybe u can include this info in the docs. Or say to upload the skin on it yourself and set it to /skinlib/show/ID, where ID is the ID of the challenge skin

**Comment by evan-goode** [comment]
> And I can use my authlib injector auth server as fallback to allow either, so i can migrate my players over time before full deprecation of the authlib injector server?

Yes that's intended to work (eventually), though I haven't tested falling back to an authlib-injector server yet.

**Comment by catfromplan9** [comment]
> > And I can use my authlib injector auth server as fallback to allow either, so i can migrate my players over time before full deprecation of the authlib injector server?
> 
> Yes that's intended to work (eventually), though I haven't tested falling back to an authlib-injector server yet.

Could it possibly work rn? I can test it

**Comment by evan-goode** [comment]
> And maybe u can include this info in the docs. Or say to upload the skin on it yourself and set it to /skinlib/show/ID, where ID is the ID of the challenge skin

Yeah will do. But no, that wouldn't work since every challenge skin is different, to prevent an attacker from registering a victim's account right after the victim sets their skin. I think a link to the "set skin" page is convenient enough.

>Could it possibly work rn? I can test it

Go for it, let me know. I'm guessing some routes may be missing/not standardized on the authlib injector side but we'll see

I should probably make a matrix room huh
